### ISSUE TITLE
Team pages don't work

### ISSUE THREAD

**Issue by nicop2pu** [p2pu/p2pu-search-cards#12]
http://p2pu.org/knls
http://p2pu.org/kclearningcircles

both links show team page name, but show all learning circles and not just those associated with the team.

**Comment by GrifP** [comment]
@nicop2pu can you move this issue to the learning-circles repo?

**Comment by nicop2pu** [comment]
@dirkcuys suggested I add it here?

**Comment by s-kennedy** [comment]
here is good, I can take this one.
